"use server";

import { Prisma } from "@prisma/client";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { db } from "@/lib/db";
import { requireAdmin } from "@/lib/actions/admin-guard";
import { EQUIPMENT_PHOTO_TYPES, parseEquipmentForm } from "@/lib/equipment";
import { removeEquipmentPhoto, saveEquipmentPhoto } from "@/lib/uploads";

type ActionResult = { error: string } | undefined;

const DUPLICATE_SAP = "Já existe um equipamento cadastrado com este Código SAP.";

function isUniqueViolation(error: unknown) {
  return error instanceof Prisma.PrismaClientKnownRequestError && error.code === "P2002";
}

async function readPhoto(formData: FormData): Promise<{ file: File | null; error?: string }> {
  const photo = formData.get("photo");
  if (!(photo instanceof File) || photo.size === 0) return { file: null };
  if (!EQUIPMENT_PHOTO_TYPES.includes(photo.type)) {
    return { file: null, error: "Formato de imagem não suportado. Use JPG, PNG ou WEBP." };
  }
  return { file: photo };
}

async function cleanupPhoto(path: string | null) {
  if (!path) return;
  await removeEquipmentPhoto(path).catch((error) =>
    console.error("Falha ao limpar foto do equipamento:", error),
  );
}

export async function createEquipmentAction(formData: FormData): Promise<ActionResult> {
  await requireAdmin();

  const parsed = parseEquipmentForm(formData);
  if (!parsed.success) return { error: parsed.error.issues[0].message };

  const { file, error: photoError } = await readPhoto(formData);
  if (photoError) return { error: photoError };

  if (await db.equipment.findUnique({ where: { codigoSap: parsed.data.codigoSap } })) {
    return { error: DUPLICATE_SAP };
  }

  let photoUrl: string | null = null;
  try {
    photoUrl = file ? await saveEquipmentPhoto(file) : null;
  } catch (error) {
    return { error: error instanceof Error ? error.message : "Falha ao enviar a foto." };
  }

  let id: string;
  try {
    // qrIdentifier is generated by the database default (UUID) — never
    // derived from user input — so the public URL is unique and stable.
    const equipment = await db.equipment.create({ data: { ...parsed.data, photoUrl } });
    id = equipment.id;
  } catch (error) {
    await cleanupPhoto(photoUrl);
    if (isUniqueViolation(error)) return { error: DUPLICATE_SAP };
    throw error;
  }

  revalidatePath("/admin/equipamentos");
  redirect(`/admin/equipamentos/${id}?salvo=1`);
}

export async function updateEquipmentAction(id: string, formData: FormData): Promise<ActionResult> {
  await requireAdmin();

  const existing = await db.equipment.findUnique({ where: { id } });
  if (!existing) return { error: "Equipamento não encontrado." };

  const parsed = parseEquipmentForm(formData);
  if (!parsed.success) return { error: parsed.error.issues[0].message };

  const { file, error: photoError } = await readPhoto(formData);
  if (photoError) return { error: photoError };

  const duplicate = await db.equipment.findUnique({ where: { codigoSap: parsed.data.codigoSap } });
  if (duplicate && duplicate.id !== id) return { error: DUPLICATE_SAP };

  let newPhoto: string | null = null;
  try {
    newPhoto = file ? await saveEquipmentPhoto(file) : null;
  } catch (error) {
    return { error: error instanceof Error ? error.message : "Falha ao enviar a foto." };
  }

  const removePhoto = formData.get("removeImage") === "true";
  const photoUrl = newPhoto ?? (removePhoto ? null : existing.photoUrl);

  try {
    // qrIdentifier is intentionally not updatable: printed labels keep working.
    await db.equipment.update({ where: { id }, data: { ...parsed.data, photoUrl } });
  } catch (error) {
    await cleanupPhoto(newPhoto);
    if (isUniqueViolation(error)) return { error: DUPLICATE_SAP };
    throw error;
  }

  if (existing.photoUrl && existing.photoUrl !== photoUrl) {
    await cleanupPhoto(existing.photoUrl);
  }

  revalidatePath("/admin/equipamentos");
  revalidatePath(`/admin/equipamentos/${id}`);
  revalidatePath(`/equipamento/${existing.qrIdentifier}`);
  redirect(`/admin/equipamentos/${id}?salvo=1`);
}

export async function deleteEquipmentAction(id: string) {
  await requireAdmin();

  const existing = await db.equipment.findUnique({ where: { id } });
  if (existing) {
    await db.equipment.delete({ where: { id } });
    await cleanupPhoto(existing.photoUrl);
    revalidatePath(`/equipamento/${existing.qrIdentifier}`);
  }

  revalidatePath("/admin/equipamentos");
  redirect("/admin/equipamentos");
}
